version: "3"

services:
  message-service:
    image: message-service:latest
    tty: true

  user-service:
    image: user-service:latest
    command:
      - "--mysql.address=192.168.1.112"
    tty: true

  user-edge-service:
    image: user-edge-service:latest
    links:
      - user-service
      - message-service
    command:
      - "--redis.address=192.168.1.112"
    tty: true

  course-service:
    image: course-service:latest
    links:
      - user-service
    command:
      - "--mysql.address=192.168.1.112"
      - "--zookeeper.address=192.168.1.112"
    tty: true

  course-edge-service:
    image: course-edge-service:latest
    links:
      - user-edge-service
    command:
      - "--zookeeper.address=192.168.1.112"
    tty: true

  api-gateway-zuul:
    image: api-gateway-zuul:latest
    links:
      - user-edge-service
      - course-edge-service
    ports:
      - 8080:8080
    tty: true