spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thrift_user?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  dubbo:
    application:
      name: courses-service
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      host: 127.0.0.1
      port: 20880
#    scan:
#      base-packages: com.course_dubbo

thrift:
  user:
    ip: 127.0.0.1
    port: 7911

#dubbo:
#  application:
#    name: courses-service
#  registry:
#    protocol: zookeeper
#    address: 127.0.0.1:2181
#  protocol:
#    name: dubbo
#    host: 127.0.0.1
#    port: 20880
#  monitor:
#    protocol: registry

server:
  port: 8083
