spring:
  application:
    name: user-thrift-service
  datasource:
    url: jdbc:mysql://${mysql.address}:3306/thrift_user?useUnicode=true&characterEncoding=utf8
    username: root
    password: docker
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 7911
