server:
  port: 8081
spring:
  dubbo:
    application:
      name: course-edge-service
    registry:
      address: zookeeper://${zookeeper.address}:2181
    scan: com.courses.course_edge
  jackson:
    default-property-inclusion: non_null