thrift:
  user:
    ip: user-service
    port: 7911
  message:
    ip: message-service
    port: 9090

timeout:
  mobile: 600
  email: 1200

spring:
  redis:
    host: ${redis.address}
    port: 6379
    timeout: 30000
    password: redis
  application:
    name: user-edge-services
server:
  port: 8082
