thrift:
  user:
    ip: 127.0.0.1
    port: 7911
  message:
    ip: 127.0.0.1
    port: 9090

timeout:
  mobile: 600
  email: 1200

spring:
  redis:
    host: localhost
    port: 6379
    timeout: 30000
  application:
    name: user-edge-service
server:
  port: 8082
